---
name: CI

on:
  pull_request:
    branches:
      - devel
      
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Cache node modules
        uses: actions/cache@v2.1.7
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint